import Foundation
import Testing
@testable import BolourCertificates

/// Loads a checked-in DER fixture (generated by scripts/generate-test-cas.sh).
enum Fixture {
    static func der(_ name: String) throws -> Data {
        let url = try #require(
            Bundle.module.url(forResource: name, withExtension: "der", subdirectory: "Fixtures"),
            "missing fixture \(name).der"
        )
        return try Data(contentsOf: url)
    }

    static func certificate(_ name: String) throws -> Certificate {
        try Certificate(derEncoded: der(name))
    }
}
