import Foundation
import Security
import BlurCertificates

/// Loads the checked-in fixtures generated by `scripts/generate-network-security-fixtures.sh`:
/// a server identity (cert + key, as PKCS12) the in-process TLS harness serves, its issuing
/// root (for `TrustEvaluator`'s test-anchors path), and a decoy certificate used only to derive
/// a plausible-but-wrong SPKI pin.
enum NetworkFixtures {
    static let pkcs12Passphrase = "blursecurity-test-fixture"

    private static func url(_ name: String, _ ext: String) -> URL {
        Bundle.module.url(forResource: name, withExtension: ext, subdirectory: "Fixtures")!
    }

    /// The `SecIdentity` (cert + private key) the local TLS harness serves. Imported straight
    /// from PKCS12 bytes in memory — never touches the persistent keychain, so it needs no
    /// entitlement and leaves no state behind.
    static func serverIdentity() throws -> SecIdentity {
        let data = try Data(contentsOf: url("server-identity", "p12"))
        let options: [String: Any] = [kSecImportExportPassphrase as String: pkcs12Passphrase]
        var rawItems: CFArray?
        let status = SecPKCS12Import(data as CFData, options as CFDictionary, &rawItems)
        guard status == errSecSuccess, let items = rawItems as? [[String: Any]],
              let first = items.first,
              let identity = first[kSecImportItemIdentity as String]
        else {
            fatalError("failed to import server-identity.p12 fixture (status \(status))")
        }
        // swiftlint:disable:next force_cast
        return (identity as! SecIdentity)
    }

    /// The root that issued the server identity — the sole anchor `TrustEvaluator` should trust
    /// in these tests, standing in for the system root store.
    static func root() throws -> Certificate {
        try Certificate(derEncoded: Data(contentsOf: url("root", "der")))
    }

    /// The server identity's own leaf, reparsed for introspection (matches what the harness serves).
    static func leaf() throws -> Certificate {
        try Certificate(derEncoded: Data(contentsOf: url("leaf", "der")))
    }

    /// An unrelated certificate — never served — used only to produce a valid-shaped SPKI pin
    /// that is guaranteed not to match the served leaf.
    static func decoy() throws -> Certificate {
        try Certificate(derEncoded: Data(contentsOf: url("decoy", "der")))
    }

    static func leafPin() throws -> SPKIHash { SPKIHash(of: try leaf()) }
    static func decoyPin() throws -> SPKIHash { SPKIHash(of: try decoy()) }
}
